name             'httpd'
maintainer       'Krzysztof Bukowski'
maintainer_email 'admin@krzysztofbukowski.pl'
license          'All rights reserved'
description      'Installs/Configures httpd'
version          '0.1.0'
